# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f220a9290bb87d5acb884618f8c762cf939d94d26d43bf60a5715cc5ecaf7941d7adb47fd2d4b137124f9afbca3b87806acfa6f95095849596ebb2ece3bab489

test:
  secret_key_base: bedde00592a97445cf3f82ad890fcaecebc0d2948aac075d0dc0e1c6164f7b9b4e081413667fad8c59d0b4f4260e3e982be7a106e838e0ccad4777cb319e467c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
